package de.pheru.darts.backend.entities.playerpermission;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "PlayerPermission")
public class PlayerPermissionEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "user_id_index")
    private String userId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "permitted_user_id_index")
    private String permittedUserId;

    public String getId() {
        return id;
    }

    public void setId(final String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(final String userId) {
        this.userId = userId;
    }

    public String getPermittedUserId() {
        return permittedUserId;
    }

    public void setPermittedUserId(final String permittedUserId) {
        this.permittedUserId = permittedUserId;
    }
}
