package de.pheru.darts.backend.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName = "Game")
public class GameEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "user_id_index")
    private String userId;

    @DynamoDBAttribute
    private Long timestamp;

    @DynamoDBAttribute
    private int score;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    private CheckOutMode checkOutMode;

    @DynamoDBAttribute
    private Boolean training;

    @DynamoDBAttribute
    private List<PlayerDocument> players;

    public String getId() {
        return id;
    }

    public void setId(final String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(final String userId) {
        this.userId = userId;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(final Long timestamp) {
        this.timestamp = timestamp;
    }

    public int getScore() {
        return score;
    }

    public void setScore(final int score) {
        this.score = score;
    }

    public CheckOutMode getCheckOutMode() {
        return checkOutMode;
    }

    public void setCheckOutMode(final CheckOutMode checkOutMode) {
        this.checkOutMode = checkOutMode;
    }

    public Boolean isTraining() {
        return training;
    }

    public void setTraining(final Boolean training) {
        this.training = training;
    }

    public List<PlayerDocument> getPlayers() {
        return players;
    }

    public void setPlayers(final List<PlayerDocument> players) {
        this.players = players;
    }
}
