package de.pheru.darts.backend.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName = "Game")
public class GameEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "user_id_index")
    private String userId;

    @DynamoDBAttribute
    private int score;

    @DynamoDBAttribute
    private String checkOutMode;

    @DynamoDBAttribute
    private String winnerId;

    @DynamoDBAttribute
    private List<PlayerDocument> players;

    public String getId() {
        return id;
    }

    public void setId(final String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(final String userId) {
        this.userId = userId;
    }

    public int getScore() {
        return score;
    }

    public void setScore(final int score) {
        this.score = score;
    }

    public String getCheckOutMode() {
        return checkOutMode;
    }

    public void setCheckOutMode(final String checkOutMode) {
        this.checkOutMode = checkOutMode;
    }

    public String getWinnerId() {
        return winnerId;
    }

    public void setWinnerId(final String winnerId) {
        this.winnerId = winnerId;
    }

    public List<PlayerDocument> getPlayers() {
        return players;
    }

    public void setPlayers(final List<PlayerDocument> players) {
        this.players = players;
    }
}
